name: Ephemeral Access Tokens for GitHub Actions
description: GitHub Action to request temporary access tokens
author: qoomon
branding:
  icon: unlock
  color: blue

inputs:
  owner:
    description: |
      Target owner e.g. octocat
      Defaults to OIDC token repository owner

  repositories:
    description: |
      Target repositories as comma separated strings
        or as a YAML array string
        or 'ALL' to target all repositories of inputs.owner .
      Defaults to OIDC token repository, only if inputs.owner is equal to OIDC token repository owner.

      Examples:

        repositories: playground, shop

        repositories: |
          - playground
          - shop

        repositories: ALL

  permissions:
    required: true
    description: |
      Permissions to request as comma separated strings
        or as YAML object string

      Examples:

        permissions: secrets:write, contents:write

        permissions: |
          secrets: write
          contents: write

  app-server:
    description: |
      Configuration of the app server endpoint.

outputs:
  token:
    description: The requested access token

runs:
  using: node24
  main: action/dist/main/index.js
  post: action/dist/post/index.js
