name: Ephemeral Access Tokens for GitHub Actions
description: GitHub Action to request temporary access tokens
author: qoomon
branding:
  icon: unlock
  color: blue

inputs:
  permissions:
    description: |
      Permissions to request as YAML object string, e.g.
      permissions: |
        secrets: write
    required: true
  repository:
    description: |
      Target repository e.g. playground
      Gets merged with repositories input
      Defaults to OIDC token repository, only if inputs.owner is equal to OIDC token repository owner
  repositories:
    description: |
      Target repositories as YAML array string or 'ALL', e.g.
      repositories: |
        - playground
        - shop
  owner:
    description: |
      Target owner e.g. octocat
      Defaults to OIDC token repository owner
  app-server:
    description: |
      Configuration of the app server endpoint.

outputs:
  token:
    description: The requested access token

runs:
  using: node20
  main: action/dist/main/index.js
  post: action/dist/post/index.js
