name: 'Access Manager for GitHub Actions'
description: 'GitHub Action to request a temporary access tokens from github access manager.'
author: 'Bengt Brodersen'
branding:
  icon: unlock
  color: blue
inputs:
  organization:
    description: 'Target organization. (e.g. sesame-street)'
    required: true
  repository:
    description: 'Target repository. (e.g. sesame-street/playground)'
    required: true
  repositories:
    description: 'Target repositories as YAML array string. (e.g. repositories: |\n  - sesame-street/playground)'
    required: true
  permissions:
    description: 'The permissions to request as YAML object string. (e.g. permissions: |\n  actions: write)'
    required: true
outputs:
  GITHUB_ACCESS_MANAGER_TOKEN:
    description: 'The requested access token'
runs:
  using: 'node20'
  main: 'action/dist/index.js'
